// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RotasViagem.Infra.Context;

#nullable disable

namespace RotasViagem.Infra.Migrations
{
    [DbContext(typeof(RotaDbContext))]
    [Migration("20250613150431_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("RotasViagem.Domain.Entities.Rota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conexao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("Destino");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("Origem");

                    b.Property<int?>("RotaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.HasIndex("RotaId");

                    b.ToTable("rota", (string)null);
                });

            modelBuilder.Entity("RotasViagem.Domain.Entities.Trecho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("Destino");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("Origem");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.HasAlternateKey("Origem", "Destino");

                    b.ToTable("trecho", (string)null);
                });

            modelBuilder.Entity("RotasViagem.Domain.Entities.Rota", b =>
                {
                    b.HasOne("RotasViagem.Domain.Entities.Rota", null)
                        .WithMany("Rotas")
                        .HasForeignKey("RotaId");
                });

            modelBuilder.Entity("RotasViagem.Domain.Entities.Rota", b =>
                {
                    b.Navigation("Rotas");
                });
#pragma warning restore 612, 618
        }
    }
}
