// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RotasViagem.Infra.Context;

#nullable disable

namespace RotasViagem.Infra.Migrations
{
    [DbContext(typeof(RotaDbContext))]
    [Migration("20250614003039_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("RotasViagem.Domain.Entities.Rota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("Destino");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("Origem");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.ToTable("rota", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
